module.exports = (stores, categoryMap) => [
  // Store 1: Parrillada Kosher Premium (Carnes a la parrilla)
  {
    name: "Parrillada Kosher Premium",
    description: "Selección de carnes kosher certificadas a la parrilla",
    price: 55.99,
    stock: 15,
    category_id: categoryMap["Carnes"],
    store_id: stores[0].id,
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
  },
  {
    name: "Asado de Tira Kosher",
    description: "Asado de tira kosher certificado, jugoso y tierno",
    price: 42.0,
    stock: 20,
    category_id: categoryMap["Carnes"],
   store_id: stores[0].id,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  },
  {
    name: "Brochetas de Cordero Kosher",
    description: "Brochetas de cordero marinado con especias orientales",
    price: 48.0,
    stock: 18,
    category_id: categoryMap["Carnes"],
   store_id: stores[0].id,
    image_url: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80",
  },
  {
    name: "Bife de Chorizo Kosher",
    description: "Corte premium de bife de chorizo kosher certificado",
    price: 52.99,
    stock: 12,
    category_id: categoryMap["Carnes"],
    store_id: stores[0].id,
    image_url: "https://comedera.com/wp-content/uploads/sites/9/2022/06/bife-de-chorizo.jpg?w=4096",
  },
  {
    name: "Costillas BBQ Kosher",
    description: "Costillas de res con salsa BBQ kosher ahumada",
    price: 58.0,
    stock: 14,
    category_id: categoryMap["Carnes"],
    store_id: stores[0].id,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  },
  {
    name: "Picaña a la Parrilla",
    description: "Picaña kosher sellada a la perfección",
    price: 61.99,
    stock: 10,
    category_id: categoryMap["Carnes"],
   store_id: stores[0].id,
    image_url: "https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80",
  },

  // Store 2: Jerusalem Flavors (Israelí/Mediterráneo)
  {
    name: "Falafel Plate",
    description: "Plato de falafel con hummus, tahini y ensalada fresca",
    price: 28.5,
    stock: 30,
    category_id: categoryMap["Platos principales"],
    store_id: stores[1].id,
    image_url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80",
  },
  {
    name: "Shawarma de Pollo",
    description: "Shawarma de pollo kosher con vegetales y salsas",
    price: 32.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
   store_id: stores[1].id,
    image_url: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80",
  },
  {
    name: "Hummus Bowl Premium",
    description: "Hummus cremoso con garbanzos enteros, aceite de oliva y pita",
    price: 24.0,
    stock: 35,
    category_id: categoryMap["Entradas"],
   store_id: stores[1].id,
    image_url: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800&q=80",
  },
  {
    name: "Sabich en Pan Pita",
    description: "Berenjena frita, huevo duro, ensalada israelí y tahini",
    price: 26.5,
    stock: 28,
    category_id: categoryMap["Platos principales"],
     store_id: stores[1].id,
    image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
  },
  {
    name: "Baba Ganoush con Pita",
    description: "Crema de berenjena ahumada con pan pita caliente",
    price: 22.0,
    stock: 32,
    category_id: categoryMap["Entradas"],
    store_id: stores[1].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfuN3np-OlxLJRyZ27XLKYoFNw8ryIyjPHEw&s",
  },
  {
    name: "Tabule Tradicional",
    description: "Ensalada de perejil, tomate, cebolla y bulgur con limón",
    price: 20.5,
    stock: 30,
    category_id: categoryMap["Ensaladas"],
   store_id: stores[1].id,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
  },
  

  // Store 3: Shabbat Kitchen (Panadería Tradicional)
  {
    name: "Jalá Tradicional",
    description: "Pan trenzado kosher para Shabbat, horneado fresco",
    price: 18.99,
    stock: 40,
    category_id: categoryMap["Panes"],
    store_id: stores[2].id,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
  },
  {
    name: "Rugelach de Chocolate",
    description: "Pastelitos tradicionales judíos rellenos de chocolate",
    price: 22.5,
    stock: 35,
    category_id: categoryMap["Dulces"],
   store_id: stores[2].id,
    image_url: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80",
  },
  {
    name: "Babka de Canela",
    description: "Pan dulce trenzado con canela y azúcar",
    price: 25.0,
    stock: 30,
    category_id: categoryMap["Panes"],
    store_id: stores[2].id,
    image_url: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=800&q=80",
  },
  {
    name: "Hamantaschen Variados",
    description: "Galletas triangulares con rellenos de fruta y amapola",
    price: 20.0,
    stock: 40,
    category_id: categoryMap["Dulces"],
  store_id: stores[2].id,
    image_url: "https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=800&q=80",
  },
  {
    name: "Jalá de Chocolate",
    description: "Pan trenzado con chips de chocolate y cacao",
    price: 21.99,
    stock: 35,
    category_id: categoryMap["Panes"],
   store_id: stores[2].id,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
  },
  {
    name: "Mandelbrot de Almendras",
    description: "Biscotti judío crujiente con almendras tostadas",
    price: 19.5,
    stock: 38,
    category_id: categoryMap["Dulces"],
   store_id: stores[2].id,
    image_url: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80",
  },
 
  // Store 4: Kosher Sushi Bar
  {
    name: "Sushi Roll Salmón",
    description: "Roll de salmón fresco certificado kosher con aguacate",
    price: 38.0,
    stock: 20,
    category_id: categoryMap["Sushi"],
    store_id: stores[3].id,
    image_url: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
  },
  {
    name: "Sashimi Mixto",
    description: "Selección de pescados frescos kosher en sashimi",
    price: 45.99,
    stock: 15,
    category_id: categoryMap["Sushi"],
   store_id: stores[3].id,
    image_url: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800&q=80",
  },
  {
    name: "California Roll Kosher",
    description: "Roll clásico con cangrejo, aguacate y pepino",
    price: 35.0,
    stock: 25,
    category_id: categoryMap["Sushi"],
     store_id: stores[3].id,
    image_url: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80",
  },
  {
    name: "Temaki de Atún",
    description: "Cono de alga nori con atún fresco y vegetales",
    price: 32.0,
    stock: 22,
    category_id: categoryMap["Sushi"],
     store_id: stores[3].id,
    image_url: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
  },
  {
    name: "Dragon Roll",
    description: "Roll de camarón tempura con aguacate y salsa de anguila",
    price: 42.0,
    stock: 18,
    category_id: categoryMap["Sushi"],
      store_id: stores[3].id,
    image_url: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
  },
  {
    name: "Nigiri de Salmón",
    description: "5 piezas de nigiri con salmón fresco",
    price: 36.0,
    stock: 24,
    category_id: categoryMap["Sushi"],
  store_id: stores[3].id,
    image_url: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800&q=80",
  },
 
];
