module.exports = (stores, categoryMap) => [
  // Store 13: Vegan Fast Food
  {
    name: "Burger Beyond con Queso",
    description: "Hamburguesa plant-based con queso cashew y vegetales frescos",
    price: 28.99,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[12].id,
    image_url: "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80",
  },
  {
    name: "Tacos de Proteína Vegetal",
    description: "Tacos con carne vegetal, guacamole y pico de gallo",
    price: 24.0,
    stock: 30,
    category_id: categoryMap["Platos principales"],
    store_id: stores[12].id,
    image_url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
  },
  {
    name: "Wrap de Falafel Mediterráneo",
    description: "Wrap integral con falafel crujiente, hummus y ensalada",
    price: 22.5,
    stock: 28,
    category_id: categoryMap["Platos principales"],
    store_id: stores[12].id,
    image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
  },
  {
    name: "Nuggets Crujientes",
    description: "Nuggets de proteína vegetal con salsa barbacoa",
    price: 19.0,
    stock: 35,
    category_id: categoryMap["Entradas"],
    store_id: stores[12].id,
    image_url: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80",
  },
  {
    name: "Pizza Margarita",
    description: "Pizza con mozzarella de anacardos y albahaca fresca",
    price: 26.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[12].id,
    image_url: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
  },
  {
    name: "Papas Fritas con Queso",
    description: "Papas crujientes con queso fundido y cebollín",
    price: 15.5,
    stock: 40,
    category_id: categoryMap["Entradas"],
    store_id: stores[12].id,
    image_url: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80",
  },

  // Store 14: Vegan Bowl Co.
  {
    name: "Bowl Mediterráneo",
    description: "Falafel, hummus, tabulé y vegetales de temporada",
    price: 26.5,
    stock: 30,
    category_id: categoryMap["Bowls"],
    store_id: stores[13].id,
    image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
  },
  {
    name: "Buddha Bowl Completo",
    description: "Quinoa, tofu marinado, aguacate y vegetales asados",
    price: 28.0,
    stock: 25,
    category_id: categoryMap["Bowls"],
    store_id: stores[13].id,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
  },
  {
    name: "Poke Bowl de Tofu",
    description: "Bowl estilo poke con tofu ahumado y edamame",
    price: 29.0,
    stock: 22,
    category_id: categoryMap["Bowls"],
    store_id: stores[13].id,
    image_url: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80",
  },
  {
    name: "Bowl Mexicano",
    description: "Arroz, frijoles negros, pico de gallo y guacamole",
    price: 27.0,
    stock: 28,
    category_id: categoryMap["Bowls"],
    store_id: stores[13].id,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
  },
  {
    name: "Bowl Asiático",
    description: "Arroz integral, tempeh glaseado y vegetales salteados",
    price: 28.5,
    stock: 24,
    category_id: categoryMap["Bowls"],
    store_id: stores[13].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSsF8Ctkz_1vFO5AGVo5OUFjaAJyTOieGSAg&s",
  },
  {
    name: "Bowl de Lentejas",
    description: "Lentejas especiadas con espinacas y yogurt de soja",
    price: 25.5,
    stock: 26,
    category_id: categoryMap["Bowls"],
    store_id: stores[13].id,
    image_url: "https://images.unsplash.com/photo-1547496502-affa22d38842?w=800&q=80",
  },

  // Store 15: Plant Power Kitchen
  {
    name: "Pastel de Chocolate Ganache",
    description: "Bizcocho de chocolate con ganache de cacao intenso",
    price: 35.0,
    stock: 15,
    category_id: categoryMap["Postres"],
    store_id: stores[14].id,
    image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80",
  },
  {
    name: "Risotto de Hongos Silvestres",
    description: "Risotto cremoso con hongos y parmesano de anacardos",
    price: 32.0,
    stock: 18,
    category_id: categoryMap["Platos principales"],
    store_id: stores[14].id,
    image_url: "https://www.hongosporto.com.ar/img/posts/2024/11/imagen_original_risotto_cremoso_de_hongos_porto_imagen.webp",
  },
  {
    name: "Wellington de Setas",
    description: "Hojaldre relleno de setas, nueces y hierbas finas",
    price: 38.0,
    stock: 12,
    category_id: categoryMap["Platos principales"],
    store_id: stores[14].id,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
  },
  {
    name: "Tiramisú Clásico",
    description: "Tiramisú tradicional con crema de cashew y café",
    price: 28.0,
    stock: 20,
    category_id: categoryMap["Postres"],
    store_id: stores[14].id,
    image_url: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&q=80",
  },
  {
    name: "Ravioles de Espinaca",
    description: "Ravioles rellenos con espinaca y ricotta de almendras",
    price: 30.0,
    stock: 16,
    category_id: categoryMap["Platos principales"],
    store_id: stores[14].id,
    image_url: "https://images.unsplash.com/photo-1587740908075-9e245070dfaa?w=800&q=80",
  },
  {
    name: "Tarta de Limón",
    description: "Tarta con crema de limón y merengue tostado",
    price: 26.5,
    stock: 18,
    category_id: categoryMap["Postres"],
    store_id: stores[14].id,
    image_url: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800&q=80",
  },
  {
    name: "Seitan al Vino Tinto",
    description: "Seitan en reducción de vino con vegetales glaseados",
    price: 34.0,
    stock: 14,
    category_id: categoryMap["Platos principales"],
    store_id: stores[14].id,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
  },

  // Store 27: Vegan Sweets & Treats
  {
    name: "Macarons Surtidos",
    description: "Macarons en sabores pistacho, frambuesa y chocolate",
    price: 24.99,
    stock: 18,
    category_id: categoryMap["Dulces"],
    store_id: stores[15].id,
    image_url: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&q=80",
  },
  {
    name: "Cupcakes de Vainilla",
    description: "Cupcakes esponjosos con buttercream de vainilla",
    price: 20.0,
    stock: 25,
    category_id: categoryMap["Dulces"],
    store_id: stores[15].id,
    image_url: "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?w=800&q=80",
  },
  {
    name: "Donuts Glaseados",
    description: "Donuts suaves con glaseado de chocolate y sprinkles",
    price: 16.0,
    stock: 30,
    category_id: categoryMap["Dulces"],
    store_id: stores[15].id,
    image_url: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&q=80",
  },
  {
    name: "Cookies de Chips",
    description: "Galletas con chips de chocolate y nueces",
    price: 18.0,
    stock: 32,
    category_id: categoryMap["Dulces"],
    store_id: stores[15].id,
    image_url: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80",
  },
  {
    name: "Trufas de Chocolate",
    description: "Trufas de chocolate negro con cacao en polvo",
    price: 22.0,
    stock: 20,
    category_id: categoryMap["Dulces"],
    store_id: stores[15].id,
    image_url: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&q=80",
  },
  {
    name: "Alfajores de Maicena",
    description: "Alfajores rellenos con dulce de leche de coco",
    price: 19.0,
    stock: 24,
    category_id: categoryMap["Dulces"],
    store_id: stores[15].id,
    image_url: "https://notonlysaladblog.com/wp-content/uploads/2017/07/Alf-maicena-3-Large.jpg",
  },
];
