module.exports = (stores, categoryMap) => [
  // Store 9: Gluten Free Bakery
  {
    name: "Brownie de Chocolate",
    description: "Delicioso brownie con nueces y chocolate belga",
    price: 12.5,
    stock: 28,
    category_id: categoryMap["Dulces"],
    store_id: stores[8].id,
    image_url: "https://images.unsplash.com/photo-1590841609987-4ac211afdde1?w=800&q=80",
  },
  {
    name: "Pan de Molde",
    description: "Pan de molde esponjoso ideal para tostadas",
    price: 18.0,
    stock: 25,
    category_id: categoryMap["Panes"],
    store_id: stores[8].id,
    image_url:
      "https://tastyfree.cl/cdn/shop/files/pan_molde_multigrano_Largo.webp?v=1693273384&width=3840",
  },
  {
    name: "Galletas de Almendra",
    description: "Galletas crujientes de harina de almendra",
    price: 14.5,
    stock: 30,
    category_id: categoryMap["Dulces"],
    store_id: stores[8].id,
    image_url: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80",
  },
  {
    name: "Muffins Variados",
    description: "Set de muffins de arándanos, chocolate y limón",
    price: 16.0,
    stock: 24,
    category_id: categoryMap["Dulces"],
    store_id: stores[8].id,
    image_url: "https://images.unsplash.com/photo-1426869884541-df7117556757?w=800&q=80",
  },
  {
    name: "Torta Red Velvet",
    description: "Torta red velvet con frosting de queso crema",
    price: 32.0,
    stock: 12,
    category_id: categoryMap["Dulces"],
    store_id: stores[8].id,
    image_url: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=800&q=80",
  },
  {
    name: "Croissants Hojaldrados",
    description: "Croissants mantecosos y crujientes",
    price: 15.5,
    stock: 20,
    category_id: categoryMap["Panes"],
    store_id: stores[8].id,
    image_url: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80",
  },

  // Store 10: Celiac Heaven
  {
    name: "Pan Artesanal con Semillas",
    description: "Pan artesanal con mix de semillas",
    price: 15.99,
    stock: 20,
    category_id: categoryMap["Panes"],
    store_id: stores[9].id,
    image_url: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=800&q=80",
  },
  {
    name: "Empanadas de Carne",
    description: "Empanadas de carne jugosas con masa casera, gluten free",
    price: 22.0,
    stock: 25,
    category_id: categoryMap["Entradas"],
    store_id: stores[9].id,
    image_url: "https://www.goya.com/wp-content/uploads/2023/10/spinachempanadas.jpg",
  },
  {
    name: "Torta de Zanahoria",
    description: "Torta de zanahoria con frosting de queso crema",
    price: 28.0,
    stock: 15,
    category_id: categoryMap["Dulces"],
    store_id: stores[9].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWEgDTvyupgL--kv5L5DQ_WCtByvMynC9Z9Q&s",
  },
  {
    name: "Ñoquis de Papa",
    description: "Ñoquis caseros de papa (porción para 2)",
    price: 24.0,
    stock: 20,
    category_id: categoryMap["Entradas"],
    store_id: stores[9].id,
    image_url:
      "https://www.lavoz.com.ar/resizer/v2/FR6ZE5GQF5CLFJJZ3O63WAYG64.jpg?auth=37d5d0a1a7952b84776d4c5c1d686955f940c2771c742a6c1356846cddc4273d&quality=75&smart=true&width=385",
  },
  {
    name: "Panqueques (6 unidades)",
    description: "Panqueques listos para rellenar",
    price: 18.0,
    stock: 22,
    category_id: categoryMap["Entradas"],
    store_id: stores[9].id,
    image_url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
  },
  {
    name: "Polvorones Tradicionales",
    description: "Polvorones que se deshacen en la boca",
    price: 13.5,
    stock: 28,
    category_id: categoryMap["Dulces"],
    store_id: stores[9].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdvKFDmAIfb69D1HMe7y8SZdIi7zQ9YQfIag&s",
  },

  // Store 11: GF Pizza House
  {
    name: "Pizza Margarita",
    description: "Pizza clásica con salsa de tomate y mozzarella, gluten free",
    price: 32.0,
    stock: 18,
    category_id: categoryMap["Pizzas"],
    store_id: stores[10].id,
    image_url: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
  },
  {
    name: "Pizza Pepperoni",
    description: "Pizza con pepperoni y queso extra, gluten free",
    price: 35.0,
    stock: 16,
    category_id: categoryMap["Pizzas"],
    store_id: stores[10].id,
    image_url: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&q=80",
  },
  {
    name: "Pizza Vegetariana",
    description: "Pizza con vegetales asados de estación, gluten free",
    price: 33.0,
    stock: 20,
    category_id: categoryMap["Pizzas"],
    store_id: stores[10].id,
    image_url: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800&q=80",
  },
  {
    name: "Pizza Cuatro Quesos",
    description: "Pizza con mozzarella, gorgonzola, parmesano y fontina, gluten free",
    price: 36.0,
    stock: 15,
    category_id: categoryMap["Pizzas"],
    store_id: stores[10].id,
    image_url: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
  },
  {
    name: "Pizza Napolitana",
    description: "Pizza con tomate, ajo y albahaca fresca, gluten free",
    price: 31.0,
    stock: 22,
    category_id: categoryMap["Pizzas"],
    store_id: stores[10].id,
    image_url: "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?w=800&q=80",
  },
  {
    name: "Pizza Hawaiana",
    description: "Pizza con jamón y ananá",
    price: 34.0,
    stock: 18,
    category_id: categoryMap["Pizzas"],
    store_id: stores[10].id,
    image_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
  },

  // Store 12: Pasta Without Limits
  {
    name: "Ravioles de Ricota",
    description: "Ravioles caseros rellenos de ricota (porción 250g)",
    price: 28.0,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[11].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOi2jbF8G2U_koWS6XgD3rSpZmAXJAPZEL_Q&s",
  },
  {
    name: "Lasaña de Carne",
    description: "Lasaña casera con salsa bolognesa",
    price: 32.0,
    stock: 18,
    category_id: categoryMap["Platos principales"],
    store_id: stores[11].id,
    image_url: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&q=80",
  },
  {
    name: "Cheesecake de Frutos Rojos",
    description: "Cheesecake cremoso con coulis de frutos rojos",
    price: 28.5,
    stock: 16,
    category_id: categoryMap["Dulces"],
    store_id: stores[11].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWs_f0aCDFzcaZbIkuwDJlS63uA_-q4XcZ3g&s",
  },
  {
    name: "Sorrentinos de Jamón y Queso",
    description: "Sorrentinos rellenos con jamón y mozzarella (250g)",
    price: 29.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[11].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfmcpxHV2JK2l5krjy-1fIDUjRRX_t2WqC-g&s",
  },
  {
    name: "Fetuccini Frescos",
    description: "Fetuccini caseros (porción 300g)",
    price: 22.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[11].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxJ-7DL9R1vUqpg_yNMR941dCMjKFUnNKssQ&s",
  },
  {
    name: "Canelones de Verdura",
    description: "Canelones rellenos de espinaca y ricota",
    price: 30.0,
    stock: 18,
    category_id: categoryMap["Platos principales"],
    store_id: stores[11].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7SCiaB5SJ9UVXi6SH7VpMs1wQGQU7MRw77A&s",
  },
];
