module.exports = (stores, categoryMap) => [
  // Store 5: Sugar Free Zone
  {
    name: "Ensalada Power Bowl",
    description: "Bowl nutritivo con quinoa, vegetales frescos y proteína magra",
    price: 24.5,
    stock: 30,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
  },
  {
    name: "Salmón con Vegetales al Vapor",
    description: "Filete de salmón fresco con brócoli y espárragos",
    price: 35.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
  },
  {
    name: "Wrap de Pollo Integral",
    description: "Wrap de tortilla integral con pollo grillado y vegetales crujientes",
    price: 22.0,
    stock: 28,
    category_id: categoryMap["Wraps"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
  },
  {
    name: "Mousse de Limón",
    description: "Mousse cremoso de limón con textura suave",
    price: 18.5,
    stock: 25,
    category_id: categoryMap["Postres"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  },
  {
    name: "Pollo al Curry con Vegetales",
    description: "Pechuga de pollo en salsa de curry suave con vegetales mixtos",
    price: 27.0,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
  },
  {
    name: "Sopa de Lentejas Casera",
    description: "Sopa reconfortante de lentejas con vegetales frescos",
    price: 16.0,
    stock: 35,
    category_id: categoryMap["Sopas"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
  },
  {
    name: "Yogurt Parfait con Frutos Rojos",
    description: "Yogurt griego natural con arándanos, fresas y granola",
    price: 14.5,
    stock: 40,
    category_id: categoryMap["Brunch"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  },
  {
    name: "Hamburguesa de Pavo con Ensalada",
    description: "Hamburguesa de pavo magro servida con ensalada fresca",
    price: 23.0,
    stock: 26,
    category_id: categoryMap["Platos principales"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
  },
  {
    name: "Gelatina con Frutas Frescas",
    description: "Gelatina ligera acompañada de frutas de estación",
    price: 12.0,
    stock: 45,
    category_id: categoryMap["Postres"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80",
  },
  {
    name: "Brochetas de Pollo y Vegetales",
    description: "Brochetas mixtas de pollo marinado con pimientos y calabacín",
    price: 25.0,
    stock: 24,
    category_id: categoryMap["Platos principales"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1633964913295-ceb43826844c?w=800&q=80",
  },
  {
    name: "Flan Casero",
    description: "Flan tradicional de vainilla con textura cremosa",
    price: 15.0,
    stock: 30,
    category_id: categoryMap["Postres"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=800&q=80",
  },
  {
    name: "Ensalada César con Pollo",
    description: "Ensalada clásica con pollo grillado, lechuga romana y aderezo ligero",
    price: 21.0,
    stock: 28,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80",
  },
  {
    name: "Tarta de Queso con Frutos Rojos",
    description: "Cheesecake cremoso con base de almendras y topping de berries",
    price: 26.0,
    stock: 20,
    category_id: categoryMap["Dulces"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=800&q=80",
  },
  {
    name: "Merluza al Horno con Limón",
    description: "Filete de merluza al horno con hierbas y rodajas de limón",
    price: 29.0,
    stock: 18,
    category_id: categoryMap["Platos principales"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
  },
  {
    name: "Panqueques de Avena con Fruta",
    description: "Panqueques integrales servidos con frutas frescas",
    price: 17.5,
    stock: 32,
    category_id: categoryMap["Dulces"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
  },

  // Store 6: Balanced Bites
  {
    name: "Pollo Grillado con Vegetales",
    description: "Pechuga de pollo a la parrilla con vegetales al vapor",
    price: 28.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&q=80",
  },
  {
    name: "Ensalada Mediterránea",
    description: "Ensalada con queso feta, aceitunas, tomate y pepino",
    price: 21.5,
    stock: 30,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
  },
  {
    name: "Bowl de Proteínas",
    description: "Bowl completo con huevos, aguacate, salmón y espinaca fresca",
    price: 26.0,
    stock: 22,
    category_id: categoryMap["Bowls"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80",
  },
  {
    name: "Atún a la Plancha con Ensalada",
    description: "Filete de atún sellado con mezcla de hojas verdes",
    price: 32.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1580959375944-1ab5eeb1d61b?w=800&q=80",
  },
  {
    name: "Omelette de Vegetales",
    description: "Omelette esponjoso con champiñones, espinaca y tomate",
    price: 18.0,
    stock: 35,
    category_id: categoryMap["Brunch"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
  },
  {
    name: "Crema de Brócoli",
    description: "Crema suave de brócoli con toque de ajo",
    price: 15.0,
    stock: 28,
    category_id: categoryMap["Sopas"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
  },
  {
    name: "Pavo al Horno con Hierbas",
    description: "Pechuga de pavo asada con romero y tomillo",
    price: 30.0,
    stock: 18,
    category_id: categoryMap["Platos principales"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=800&q=80",
  },
  {
    name: "Yogurt con Nueces y Canela",
    description: "Yogurt griego natural con nueces tostadas y un toque de canela",
    price: 13.0,
    stock: 40,
    category_id: categoryMap["Brunch"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  },
  {
    name: "Ensalada Griega",
    description: "Ensalada tradicional con queso feta, aceitunas y orégano",
    price: 20.0,
    stock: 32,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1580013759032-c96505e24c1f?w=800&q=80",
  },
  {
    name: "Brownie de Chocolate",
    description: "Brownie húmedo de chocolate amargo",
    price: 16.0,
    stock: 25,
    category_id: categoryMap["Dulces"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1590841609987-4ac211afdde1?w=800&q=80",
  },
  {
    name: "Calabaza Asada con Especias",
    description: "Cubos de calabaza al horno con mezcla de especias",
    price: 14.0,
    stock: 30,
    category_id: categoryMap["Acompañamientos"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1570463246009-e235e32f3cb2?w=800&q=80",
  },
  {
    name: "Wrap de Vegetales Asados",
    description: "Tortilla integral rellena de vegetales asados y hummus",
    price: 19.5,
    stock: 26,
    category_id: categoryMap["Wraps"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
  },
  {
    name: "Pudín de Chía con Vainilla",
    description: "Pudín de semillas de chía con leche de almendras y vainilla",
    price: 14.5,
    stock: 35,
    category_id: categoryMap["Postres"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80",
  },
  {
    name: "Pescado al Papillote",
    description: "Pescado blanco cocido al vapor con vegetales en papel",
    price: 31.0,
    stock: 16,
    category_id: categoryMap["Platos principales"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
  },
  {
    name: "Frutos Rojos con Crema",
    description: "Mix de fresas, arándanos y frambuesas con crema batida",
    price: 15.5,
    stock: 28,
    category_id: categoryMap["Postres"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1464454709131-ffd692591ee5?w=800&q=80",
  },

  // Store 7: Diabetic Gourmet
  {
    name: "Filete Mignon con Vegetales",
    description: "Filete mignon gourmet con vegetales asados selectos",
    price: 48.0,
    stock: 15,
    category_id: categoryMap["Platos principales"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
  },
  {
    name: "Risotto de Quinoa",
    description: "Risotto cremoso preparado con quinoa y parmesano",
    price: 32.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1476124369491-c4fbf423085d?w=800&q=80",
  },
  {
    name: "Tarta de Almendras",
    description: "Tarta artesanal de almendras con textura húmeda",
    price: 28.0,
    stock: 18,
    category_id: categoryMap["Dulces"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?w=800&q=80",
  },
  {
    name: "Cordero al Romero",
    description: "Rack de cordero con costra de hierbas y vegetales gourmet",
    price: 52.0,
    stock: 12,
    category_id: categoryMap["Platos principales"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80",
  },
  {
    name: "Ensalada de Espinaca y Frutos Secos",
    description: "Mix de espinaca baby, nueces, queso de cabra y vinagreta",
    price: 24.0,
    stock: 22,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&q=80",
  },
  {
    name: "Mousse de Chocolate Amargo",
    description: "Mousse de chocolate 85% cacao con textura sedosa",
    price: 22.0,
    stock: 20,
    category_id: categoryMap["Postres"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800&q=80",
  },
  {
    name: "Vieiras a la Plancha",
    description: "Vieiras frescas selladas con reducción de limón",
    price: 44.0,
    stock: 14,
    category_id: categoryMap["Platos principales"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1559737558-2f5a555ae5b4?w=800&q=80",
  },
  {
    name: "Sopa de Calabaza Gourmet",
    description: "Crema de calabaza con aceite de trufa y semillas tostadas",
    price: 19.0,
    stock: 25,
    category_id: categoryMap["Sopas"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800&q=80",
  },
  {
    name: "Bacalao Confitado",
    description: "Lomo de bacalao confitado en aceite de oliva con ajo",
    price: 38.0,
    stock: 16,
    category_id: categoryMap["Platos principales"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
  },
  {
    name: "Trufas de Cacao y Aguacate",
    description: "Trufas artesanales de cacao puro y aguacate",
    price: 18.0,
    stock: 30,
    category_id: categoryMap["Dulces"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1548848979-47519fe7dfb8?w=800&q=80",
  },
  {
    name: "Carpaccio de Res",
    description: "Finas láminas de res con rúcula, parmesano y aceite de oliva",
    price: 26.0,
    stock: 18,
    category_id: categoryMap["Entradas"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  },
  {
    name: "Parfait de Yogurt Griego Premium",
    description: "Yogurt griego con granola artesanal y frutas exóticas",
    price: 21.0,
    stock: 20,
    category_id: categoryMap["Brunch"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  },
  {
    name: "Peras al Vino con Especias",
    description: "Peras cocidas en reducción de vino con canela y clavo",
    price: 20.0,
    stock: 15,
    category_id: categoryMap["Postres"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&q=80",
  },
  {
    name: "Ensalada Caprese Premium",
    description: "Tomates heirloom, mozzarella de búfala y albahaca fresca",
    price: 23.0,
    stock: 24,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800&q=80",
  },
  {
    name: "Tarta de Limón",
    description: "Tarta con crema de limón sobre base de almendras",
    price: 25.0,
    stock: 16,
    category_id: categoryMap["Dulces"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80",
  },

  // Store 8: Healthy Carbs
  {
    name: "Bowl de Avena Proteica",
    description: "Avena con proteína en polvo, nueces y frutos rojos",
    price: 19.5,
    stock: 35,
    category_id: categoryMap["Brunch"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=800&q=80",
  },
  {
    name: "Batido Verde Energizante",
    description: "Smoothie de espinaca, pepino, manzana verde y jengibre",
    price: 16.0,
    stock: 40,
    category_id: categoryMap["Bebidas"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800&q=80",
  },
  {
    name: "Pasta Integral con Pesto",
    description: "Pasta de trigo integral con salsa pesto de albahaca fresca",
    price: 24.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
  },
  {
    name: "Tostadas Integrales con Aguacate",
    description: "Pan integral tostado con aguacate, tomate y semillas",
    price: 17.0,
    stock: 30,
    category_id: categoryMap["Brunch"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80",
  },
  {
    name: "Bowl de Quinoa y Vegetales",
    description: "Quinoa tricolor con vegetales asados y semillas de sésamo",
    price: 22.0,
    stock: 28,
    category_id: categoryMap["Bowls"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
  },
  {
    name: "Batido de Proteína con Berries",
    description: "Smoothie de proteína vegetal con frutos del bosque",
    price: 180,
    stock: 35,
    category_id: categoryMap["Bebidas"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800&q=80",
  },
  {
    name: "Ensalada de Garbanzos",
    description: "Garbanzos con vegetales frescos, limón y aceite de oliva",
    price: 190,
    stock: 32,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
  },
  {
    name: "Pan Integral de Semillas",
    description: "Pan casero integral con semillas de girasol, lino y chía",
    price: 150,
    stock: 20,
    category_id: categoryMap["Panes"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
  },
  {
    name: "Galletas de Avena y Pasas",
    description: "Galletas crujientes de avena integral con pasas",
    price: 130,
    stock: 40,
    category_id: categoryMap["Dulces"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80",
  },
  {
    name: "Wrap de Hummus y Vegetales",
    description: "Tortilla integral con hummus casero y vegetales crujientes",
    price: 185,
    stock: 26,
    category_id: categoryMap["Wraps"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
  },
  {
    name: "Barras Energéticas de Frutos Secos",
    description: "Barras caseras de almendras, nueces y semillas",
    price: 120,
    stock: 45,
    category_id: categoryMap["Dulces"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1614967424664-36375f5cb346?w=800&q=80",
  },
  {
    name: "Arroz Integral con Vegetales",
    description: "Arroz integral salteado con mix de vegetales frescos",
    price: 200,
    stock: 24,
    category_id: categoryMap["Platos principales"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1516684669134-de6f7c473a2a?w=800&q=80",
  },
  {
    name: "Muffins de Arándanos Integrales",
    description: "Muffins esponjosos de harina integral con arándanos frescos",
    price: 140,
    stock: 30,
    category_id: categoryMap["Dulces"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&q=80",
  },
  {
    name: "Sopa de Verduras con Legumbres",
    description: "Sopa nutritiva con mix de verduras frescas y legumbres",
    price: 165,
    stock: 28,
    category_id: categoryMap["Sopas"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
  },
  {
    name: "Bowl de Yogurt con Granola",
    description: "Yogurt natural con granola casera y frutas de temporada",
    price: 155,
    stock: 35,
    category_id: categoryMap["Brunch"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  },

  // Store 25: Sweet Life Sugar Free
  {
    name: "Brownie de Chocolate",
    description: "Brownie húmedo de chocolate amargo intenso",
    price: 150,
    stock: 30,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1590841609987-4ac211afdde1?w=800&q=80",
  },
  {
    name: "Galletas de Avena",
    description: "Galletas crujientes de avena con textura perfecta",
    price: 129,
    stock: 35,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80",
  },
  {
    name: "Cheesecake de Vainilla",
    description: "Cheesecake cremoso de vainilla sobre base de galleta",
    price: 240,
    stock: 20,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=800&q=80",
  },
  {
    name: "Muffins de Chocolate",
    description: "Muffins esponjosos con chips de chocolate",
    price: 135,
    stock: 28,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&q=80",
  },
  {
    name: "Tarta de Fresas",
    description: "Tarta fresca con crema y fresas naturales",
    price: 260,
    stock: 18,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80",
  },
  {
    name: "Cookies de Chips de Chocolate",
    description: "Galletas suaves con chips de chocolate amargo",
    price: 140,
    stock: 32,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80",
  },
  {
    name: "Cheesecake de Frutos Rojos",
    description: "Cheesecake con topping de arándanos y fresas",
    price: 250,
    stock: 22,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1533134242820-b4f65db479a8?w=800&q=80",
  },
  {
    name: "Alfajores de Maicena",
    description: "Alfajores suaves rellenos de dulce de leche especial",
    price: 160,
    stock: 25,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=800&q=80",
  },
  {
    name: "Tarta de Limón Merengada",
    description: "Tarta cremosa de limón con merengue italiano",
    price: 230,
    stock: 20,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?w=800&q=80",
  },
  {
    name: "Bombones de Chocolate",
    description: "Bombones artesanales de chocolate premium",
    price: 190,
    stock: 30,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1548848979-47519fe7dfb8?w=800&q=80",
  },
  {
    name: "Cupcakes de Vainilla",
    description: "Cupcakes decorados con frosting de vainilla",
    price: 145,
    stock: 28,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=800&q=80",
  },
  {
    name: "Tarta de Manzana Casera",
    description: "Tarta tradicional de manzanas con canela",
    price: 220,
    stock: 16,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=800&q=80",
  },
  {
    name: "Macarons Surtidos",
    description: "Delicados macarons franceses en variedad de sabores",
    price: 180,
    stock: 24,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&q=80",
  },
  {
    name: "Panettone Clásico",
    description: "Panettone esponjoso con frutas confitadas",
    price: 280,
    stock: 15,
    category_id: categoryMap["Dulces"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1608197243236-7171aaf18d9a?w=800&q=80",
  },
  {
    name: "Tiramisú Tradicional",
    description: "Tiramisú italiano con café y cacao",
    price: 210,
    stock: 20,
    category_id: categoryMap["Postres"],
    store_id: stores[24].id,
    image_url: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&q=80",
  },

  // Store 26: Diabetic Delight Meals

  {
    name: "Pechuga de Pavo al Horno",
    description: "Pechuga de pavo jugosa con hierbas aromáticas y vegetales",
    price: 290,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1588347818036-b6d291282eee?w=800&q=80",
  },
  {
    name: "Lasaña de Vegetales",
    description: "Lasaña con capas de vegetales y salsa de tomate casera",
    price: 260,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
  },
  {
    name: "Salmón a la Naranja",
    description: "Filete de salmón con glaseado de naranja y vegetales",
    price: 340,
    stock: 16,
    category_id: categoryMap["Platos principales"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
  },
  {
    name: "Bowl Mediterráneo Completo",
    description: "Bowl con pollo, quinoa, hummus, vegetales y tahini",
    price: 270,
    stock: 24,
    category_id: categoryMap["Bowls"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80",
  },
  {
    name: "Pollo al Limón con Alcaparras",
    description: "Pechuga de pollo en salsa de limón y alcaparras",
    price: 280,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&q=80",
  },
  {
    name: "Albóndigas de Pavo en Salsa",
    description: "Albóndigas de pavo en salsa de tomate natural con especias",
    price: 250,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80",
  },
  {
    name: "Ensalada César con Salmón",
    description: "Ensalada César con salmón grillado y aderezo ligero",
    price: 260,
    stock: 20,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80",
  },
  {
    name: "Lomo de Cerdo Magro",
    description: "Lomo de cerdo asado con vegetales de temporada",
    price: 310,
    stock: 16,
    category_id: categoryMap["Platos principales"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80",
  },
  {
    name: "Cazuela de Mariscos",
    description: "Cazuela con variedad de mariscos frescos en caldo ligero",
    price: 360,
    stock: 14,
    category_id: categoryMap["Platos principales"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1559737558-2f5a555ae5b4?w=800&q=80",
  },
  {
    name: "Ensalada de Atún y Aguacate",
    description: "Ensalada fresca con atún, aguacate y vegetales mixtos",
    price: 230,
    stock: 24,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
  },
  {
    name: "Gazpacho Andaluz",
    description: "Sopa fría de tomate, pepino y pimientos frescos",
    price: 140,
    stock: 30,
    category_id: categoryMap["Sopas"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
  },
  {
    name: "Pechugas Rellenas de Espinaca",
    description: "Pechuga de pollo rellena con espinaca y queso bajo en grasa",
    price: 200,
    stock: 18,
    category_id: categoryMap["Platos principales"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&q=80",
  },
  {
    name: "Natillas de Vainilla",
    description: "Natillas cremosas de vainilla natural",
    price: 350,
    stock: 28,
    category_id: categoryMap["Postres"],
    store_id: stores[25].id,
    image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  },
];
