module.exports = (stores, categoryMap) => [
  // Store 21: Veggie Delight Corner

  // Store 22: Garden Fresh Kitchen
  {
    name: "Ensalada Caprese Orgánica",
    description: "Tomate, mozzarella de búfala y albahaca orgánicos",
    price: 24.0,
    stock: 25,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[16].id,
    image_url: "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800&q=80",
  },
  {
    name: "Quiche de Vegetales",
    description: "Quiche con vegetales orgánicos de la huerta",
    price: 26.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[16].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNzlolEagz3Z1OeBYLzBzvF7C0YifVO2tOpA&s",
  },
  {
    name: "Wrap de Hummus",
    description: "Wrap integral con hummus casero y vegetales frescos",
    price: 21.0,
    stock: 28,
    category_id: categoryMap["Platos principales"],
    store_id: stores[16].id,
    image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
  },
  {
    name: "Bowl de Quinoa",
    description: "Quinoa con aguacate, garbanzos y vegetales asados",
    price: 27.0,
    stock: 22,
    category_id: categoryMap["Bowls"],
    store_id: stores[16].id,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
  },
  {
    name: "Ensalada Griega",
    description: "Tomate, pepino, aceitunas, cebolla y queso feta",
    price: 23.0,
    stock: 26,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[16].id,
    image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
  },
  {
    name: "Buddha Bowl",
    description: "Bowl completo con granos, vegetales y tahini",
    price: 28.0,
    stock: 20,
    category_id: categoryMap["Bowls"],
    store_id: stores[16].id,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
  },

  // Store 23: Veggie Grill & More
  {
    name: "Parrillada de Vegetales",
    description: "Mix de vegetales asados con queso halloumi grillado",
    price: 32.0,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[17].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrWcjzWNF5DBMHwBoAVxBaG7uhyJhdCIQDQQ&s",
  },
  {
    name: "Provoleta Gratinada",
    description: "Provoleta con tomates cherry y orégano",
    price: 24.0,
    stock: 25,
    category_id: categoryMap["Entradas"],
    store_id: stores[17].id,
    image_url: "https://i.ytimg.com/vi/llxi9deSMIY/maxresdefault.jpg",
  },
  {
    name: "Berenjena a la Parmesana",
    description: "Capas de berenjena con queso y salsa de tomate",
    price: 28.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[17].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzrbwQqNhwM4eI8xm2HpZWrzSVlBj3hq6KtA&s",
  },
  {
    name: "Brochetas de Tofu",
    description: "Brochetas de tofu marinado con vegetales grillados",
    price: 26.0,
    stock: 24,
    category_id: categoryMap["Platos principales"],
    store_id: stores[17].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuDVJYm2wyyMV42b8SB_a_xN3JRH4w5pBaCA&s",
  },
  {
    name: "Calabacines Rellenos",
    description: "Calabacines rellenos de arroz integral y queso",
    price: 25.0,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[17].id,
    image_url:
      "https://d36fw6y2wq3bat.cloudfront.net/recipes/calabacines-rellenos-de-arroz-y-bacon/900/calabacines-rellenos-de-arroz-y-bacon.jpg",
  },
  {
    name: "Pimientos Asados",
    description: "Pimientos rojos asados rellenos de queso de cabra",
    price: 27.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[17].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdN4vbykABDX7ZbKLPJkpTyebZGTG5ub78MA&s",
  },

  // Store 24: The Green Plate
  {
    name: "Tarta de Espinaca y Ricota",
    description: "Tarta casera de espinaca y queso ricota",
    price: 23.0,
    stock: 28,
    category_id: categoryMap["Platos principales"],
    store_id: stores[18].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkW9ZNUhaFdgwyZnIlmPa1rlCxMtYCeqoOdw&s",
  },
  {
    name: "Budín de Verduras",
    description: "Budín de vegetales con queso gratinado",
    price: 20.0,
    stock: 30,
    category_id: categoryMap["Platos principales"],
    store_id: stores[18].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAKyTX4QTV1RVP_RCKgX-qyauEdlLLUYVfFw&s",
  },
  {
    name: "Empanadas Mix",
    description: "Mix de empanadas de queso, humita y espinaca",
    price: 18.0,
    stock: 35,
    category_id: categoryMap["Entradas"],
    store_id: stores[18].id,
    image_url: "https://www.goya.com/wp-content/uploads/2023/10/spinachempanadas.jpg",
  },
  {
    name: "Pastel de Choclo",
    description: "Pastel tradicional de choclo con queso",
    price: 24.0,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[18].id,
    image_url: "https://cocina-casera.com/wp-content/uploads/2018/03/Pastel-de-choclo-con-queso-o-pastel-de-humita-2.jpg",
  },
  {
    name: "Milanesa de Berenjena",
    description: "Rodajas de berenjena empanadas y horneadas",
    price: 25.0,
    stock: 26,
    category_id: categoryMap["Platos principales"],
    store_id: stores[18].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeLIPKDUGpycDyh1qqSdEjvZq09yI4ESbrpA&s",
  },
  {
    name: "Ravioles de Ricota",
    description: "Ravioles caseros rellenos de ricota y espinaca",
    price: 27.0,
    stock: 24,
    category_id: categoryMap["Platos principales"],
    store_id: stores[18].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR9h-W08NlZG_dj1Dc34T2Q6WnR-gllbU0CQ&s",
  },
  {
    name: "Ñoquis de Papa",
    description: "Ñoquis artesanales con salsa de tomate albahaca",
    price: 26.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[19].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXbrr7mqQWYRLFFRkmcKlX1x8kyC_QO0k8lw&s",
  },
  {
    name: "Crema de Calabaza",
    description: "Sopa cremosa de calabaza con jengibre",
    price: 17.0,
    stock: 30,
    category_id: categoryMap["Sopas"],
    store_id: stores[19].id,
    image_url: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800&q=80",
  },
  {
    name: "Hummus con Crudités",
    description: "Hummus casero con bastones de vegetales",
    price: 15.0,
    stock: 32,
    category_id: categoryMap["Entradas"],
    store_id: stores[19].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjJTuWJ07VqH4O-9CeL02gqq4yW79YbyVLzg&s",
  },
  {
    name: "Ensalada César",
    description: "Lechuga romana con crutones, parmesano y aderezo césar",
    price: 21.0,
    stock: 28,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[19].id,
    image_url: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80",
  },
  {
    name: "Pasta Primavera",
    description: "Pasta con vegetales frescos de estación",
    price: 24.0,
    stock: 26,
    category_id: categoryMap["Platos principales"],
    store_id: stores[19].id,
    image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
  },
  {
    name: "Macarrones con Queso",
    description: "Mac and cheese cremoso gratinado",
    price: 23.0,
    stock: 28,
    category_id: categoryMap["Platos principales"],
    store_id: stores[19].id,
    image_url: "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800&q=80",
  },
];
