module.exports = (stores, categoryMap) => [
  // Store 5: Sugar Free Zone
  {
    name: "Ensalada Power Bowl",
    description: "Bowl nutritivo con quinoa, vegetales frescos y proteína magra",
    price: 24.5,
    stock: 30,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
  },
  {
    name: "Salmón con Vegetales al Vapor",
    description: "Filete de salmón fresco con brócoli y espárragos",
    price: 35.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
  },
  {
    name: "Wrap de Pollo Integral",
    description: "Wrap de tortilla integral con pollo grillado y vegetales crujientes",
    price: 22.0,
    stock: 28,
    category_id: categoryMap["Wraps"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
  },
  {
    name: "Mousse de Limón",
    description: "Mousse cremoso de limón con textura suave",
    price: 18.5,
    stock: 25,
    category_id: categoryMap["Postres"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  },
  {
    name: "Pollo al Curry con Vegetales",
    description: "Pechuga de pollo en salsa de curry suave con vegetales mixtos",
    price: 27.0,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
  },
  {
    name: "Sopa de Lentejas Casera",
    description: "Sopa reconfortante de lentejas con vegetales frescos",
    price: 16.0,
    stock: 35,
    category_id: categoryMap["Sopas"],
    store_id: stores[4].id,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
  },

  // Store 6: Balanced Bites
  {
    name: "Pollo Grillado con Vegetales",
    description: "Pechuga de pollo a la parrilla con vegetales al vapor",
    price: 28.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&q=80",
  },
  {
    name: "Ensalada Mediterránea",
    description: "Ensalada con queso feta, aceitunas, tomate y pepino",
    price: 21.5,
    stock: 30,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
  },
  {
    name: "Bowl de Proteínas",
    description: "Bowl completo con huevos, aguacate, salmón y espinaca fresca",
    price: 26.0,
    stock: 22,
    category_id: categoryMap["Bowls"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80",
  },
  {
    name: "Atún a la Plancha con Ensalada",
    description: "Filete de atún sellado con mezcla de hojas verdes",
    price: 32.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[5].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWCSSdO_xoCCWQHNjH3LvLdJfOpyUpmR297g&s",
  },
  {
    name: "Omelette de Vegetales",
    description: "Omelette esponjoso con champiñones, espinaca y tomate",
    price: 18.0,
    stock: 35,
    category_id: categoryMap["Brunch"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
  },
  {
    name: "Crema de Brócoli",
    description: "Crema suave de brócoli con toque de ajo",
    price: 15.0,
    stock: 28,
    category_id: categoryMap["Sopas"],
    store_id: stores[5].id,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
  },

  // Store 7: Diabetic Gourmet
  {
    name: "Filete Mignon con Vegetales",
    description: "Filete mignon gourmet con vegetales asados selectos",
    price: 48.0,
    stock: 15,
    category_id: categoryMap["Platos principales"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
  },
  {
    name: "Risotto de Quinoa",
    description: "Risotto cremoso preparado con quinoa y parmesano",
    price: 32.0,
    stock: 20,
    category_id: categoryMap["Platos principales"],
    store_id: stores[6].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh8TJIEIvGqlZefJRwMOq2OFmxOq7sUd6VjQ&s",
  },
  {
    name: "Tarta de Almendras",
    description: "Tarta artesanal de almendras con textura húmeda",
    price: 28.0,
    stock: 18,
    category_id: categoryMap["Dulces"],
    store_id: stores[6].id,
    image_url: "https://cdn.recetasderechupete.com/wp-content/uploads/2020/11/Tarta-de-almendras-portuguesa.jpg",
  },
  {
    name: "Cordero al Romero",
    description: "Rack de cordero con costra de hierbas y vegetales gourmet",
    price: 52.0,
    stock: 12,
    category_id: categoryMap["Platos principales"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80",
  },
  {
    name: "Ensalada de Espinaca y Frutos Secos",
    description: "Mix de espinaca baby, nueces, queso de cabra y vinagreta",
    price: 24.0,
    stock: 22,
    category_id: categoryMap["Ensaladas"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&q=80",
  },
  {
    name: "Mousse de Chocolate Amargo",
    description: "Mousse de chocolate 85% cacao con textura sedosa",
    price: 22.0,
    stock: 20,
    category_id: categoryMap["Postres"],
    store_id: stores[6].id,
    image_url: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800&q=80",
  },

  // Store 8: Healthy Carbs
  {
    name: "Bowl de Avena Proteica",
    description: "Avena con proteína en polvo, nueces y frutos rojos",
    price: 19.5,
    stock: 35,
    category_id: categoryMap["Brunch"],
    store_id: stores[7].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROUdIUfsxJ4jCAS88Uf89aTOyuJZ8goIYTqw&s",
  },
  {
    name: "Batido Verde Energizante",
    description: "Smoothie de espinaca, pepino, manzana verde y jengibre",
    price: 16.0,
    stock: 40,
    category_id: categoryMap["Bebidas"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800&q=80",
  },
  {
    name: "Pasta Integral con Pesto",
    description: "Pasta de trigo integral con salsa pesto de albahaca fresca",
    price: 24.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
  },
  {
    name: "Tostadas Integrales con Aguacate",
    description: "Pan integral tostado con aguacate, tomate y semillas",
    price: 17.0,
    stock: 30,
    category_id: categoryMap["Brunch"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80",
  },
  {
    name: "Bowl de Quinoa y Vegetales",
    description: "Quinoa tricolor con vegetales asados y semillas de sésamo",
    price: 22.0,
    stock: 28,
    category_id: categoryMap["Bowls"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
  },
  {
    name: "Batido de Proteína con Berries",
    description: "Smoothie de proteína vegetal con frutos del bosque",
    price: 180,
    stock: 35,
    category_id: categoryMap["Bebidas"],
    store_id: stores[7].id,
    image_url: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800&q=80",
  },
];
