module.exports = (stores, categoryMap) => [
  // Store 17: Kebab Halal
  {
    name: "Kebab Halal",
    description: "Kebab de cordero halal con pan árabe y vegetales",
    price: 32.5,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[20].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZIATT_UfvbUzKN2BxRtSCifzH_6FkaXKsuQ&s",
  },
  {
    name: "Kofta a la Parrilla",
    description: "Kofta de carne especiada grillada",
    price: 30.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[20].id,
    image_url: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80",
  },
  {
    name: "Mixed Grill Halal",
    description: "Parrillada mixta con cordero, pollo y kofta",
    price: 42.0,
    stock: 18,
    category_id: categoryMap["Platos principales"],
    store_id: stores[20].id,
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
  },
  {
    name: "Shawarma de Cordero",
    description: "Shawarma de cordero con tahini y vegetales",
    price: 28.0,
    stock: 28,
    category_id: categoryMap["Wraps"],
    store_id: stores[20].id,
    image_url: "https://www.recetas-arabes.com/base/stock/Post/1-image/1-image_small.jpg.webp",
  },
  {
    name: "Falafel Wrap",
    description: "Wrap vegetariano con falafel crujiente y salsa tahini",
    price: 24.0,
    stock: 32,
    category_id: categoryMap["Wraps"],
    store_id: stores[20].id,
    image_url:
      "https://www.shutterstock.com/image-photo/lebanese-falafel-wrap-tahini-sauce-260nw-2605014687.jpg",
  },
  {
    name: "Hummus con Carne",
    description: "Hummus cremoso con carne picada especiada",
    price: 26.0,
    stock: 24,
    category_id: categoryMap["Entradas"],
    store_id: stores[20].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCki4TEPKbLCd1AaInGoJzjQkkTUDUtaUhtw&s",
  },

  // Store 18: Istanbul Kitchen
  {
    name: "Biryani de Pollo",
    description: "Arroz basmati con pollo halal especiado al estilo indio",
    price: 28.0,
    stock: 25,
    category_id: categoryMap["Platos principales"],
    store_id: stores[21].id,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80",
  },
  {
    name: "Döner Kebab Turco",
    description: "Döner tradicional turco con carne halal",
    price: 26.0,
    stock: 30,
    category_id: categoryMap["Wraps"],
    store_id: stores[21].id,
    image_url: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80",
  },
  {
    name: "Lahmacun",
    description: "Pizza turca con carne picada y especias",
    price: 22.0,
    stock: 28,
    category_id: categoryMap["Platos principales"],
    store_id: stores[21].id,
    image_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
  },
  {
    name: "Baklava Turca",
    description: "Postre turco de hojaldre, nueces y miel",
    price: 16.0,
    stock: 35,
    category_id: categoryMap["Postres"],
    store_id: stores[21].id,
    image_url: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&q=80",
  },
  {
    name: "Pide de Queso",
    description: "Pan turco en forma de bote relleno de queso derretido",
    price: 24.0,
    stock: 26,
    category_id: categoryMap["Platos principales"],
    store_id: stores[21].id,
    image_url:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrpz4_D1enWPOCBbuEM7Ddn-cU_SYYM_lZP1UVkDNv_u5KZAN-MOQ-hNCE3S0qgAu9muk&usqp=CAU",
  },
  {
    name: "Adana Kebab",
    description: "Brocheta de carne picada especiada a la parrilla",
    price: 29.0,
    stock: 22,
    category_id: categoryMap["Platos principales"],
    store_id: stores[21].id,
    image_url: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80",
  },

  // Store 19: Arabian Nights
  {
    name: "Shawarma Halal Mixto",
    description: "Mix de carnes halal con salsa tahini y ensalada",
    price: 30.0,
    stock: 28,
    category_id: categoryMap["Wraps"],
    store_id: stores[22].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVcvEECe4M8umcFri2WwedZpJwAc9DLgTn4Q&s",
  },
  {
    name: "Mansaf",
    description: "Plato tradicional de cordero con arroz y yogurt",
    price: 38.0,
    stock: 15,
    category_id: categoryMap["Platos principales"],
    store_id: stores[22].id,
    image_url:
      "https://thumbs.dreamstime.com/z/mansaf-con-cordero-tierno-salsa-de-yogur-servido-sobre-arroz-arom%C3%A1tico-en-una-bandeja-madera-tradicional-un-famoso-plato-exhibe-393503307.jpg",
  },
  {
    name: "Mezze Árabe",
    description: "Selección de entradas árabes: hummus, baba ganoush, falafel",
    price: 32.0,
    stock: 22,
    category_id: categoryMap["Entradas"],
    store_id: stores[22].id,
    image_url: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800&q=80",
  },
  {
    name: "Kunafa",
    description: "Postre árabe de queso con jarabe dulce",
    price: 20.0,
    stock: 25,
    category_id: categoryMap["Postres"],
    store_id: stores[22].id,
    image_url: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=800&q=80",
  },
  {
    name: "Maqluba",
    description: "Arroz volteado con pollo, berenjenas y especias",
    price: 35.0,
    stock: 18,
    category_id: categoryMap["Platos principales"],
    store_id: stores[22].id,
    image_url: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&q=80",
  },
  {
    name: "Mujaddara",
    description: "Lentejas con arroz y cebolla caramelizada",
    price: 22.0,
    stock: 26,
    category_id: categoryMap["Platos principales"],
    store_id: stores[22].id,
    image_url: "https://www.petitchef.es/imgupl/recipe/mujaddara-lentejas-con-arroz-y-cebolla--lg-274564p446848.webp",
  },

  // Store 20: Halal Burger Joint
  {
    name: "Baklava Árabe",
    description: "Postre tradicional árabe con nueces y miel",
    price: 18.5,
    stock: 35,
    category_id: categoryMap["Postres"],
    store_id: stores[23].id,
    image_url: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&q=80",
  },
  {
    name: "Burger Halal Classic",
    description: "Hamburguesa de carne halal con queso y vegetales",
    price: 24.0,
    stock: 30,
    category_id: categoryMap["Carnes"],
    store_id: stores[23].id,
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
  },
  {
    name: "Double Burger Halal",
    description: "Doble carne halal con bacon de pavo y cheddar",
    price: 28.0,
    stock: 25,
    category_id: categoryMap["Carnes"],
    store_id: stores[23].id,
    image_url: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&q=80",
  },
  {
    name: "Chicken Burger Halal",
    description: "Hamburguesa de pollo crujiente con salsa especial",
    price: 22.0,
    stock: 28,
    category_id: categoryMap["Carnes"],
    store_id: stores[23].id,
    image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQca6veRxwaTlJY2EXTIgv8vxVPx-WUo7bHoQ&s",
  },
  {
    name: "BBQ Bacon Burger",
    description: "Burger con bacon halal de pavo y salsa BBQ",
    price: 26.0,
    stock: 24,
    category_id: categoryMap["Carnes"],
    store_id: stores[23].id,
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80",
  },
  {
    name: "Spicy Jalapeño Burger",
    description: "Burger picante con jalapeños y queso pepper jack",
    price: 25.0,
    stock: 26,
    category_id: categoryMap["Carnes"],
    store_id: stores[23].id,
    image_url: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&q=80",
  },
];
