const glutenFreeStores = [
  {
    id: 9,
    name: "Gluten Free Bakery",
    description: "Panadería 100% libre de gluten. Pan, pasteles y galletas que saben increíbles.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    category: "gluten-free",
    rating: 4.9,
    deliveryTime: "30-40 min",
    deliveryFee: 0,
    featured: true,
    tags: ["Panadería", "Sin TACC", "Certificado"],
    address: "Punta Carretas, Solano García 2567, Montevideo",
    phone: "+598 2711 2345",
    email: "info@glutenfreebakery.com.uy"
  },
  {
    id: 10,
    name: "Celiac Heaven",
    description: "Cocina dedicada sin contaminación cruzada. Certificado por asociación de celíacos.",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    category: "gluten-free",
    rating: 4.8,
    deliveryTime: "35-45 min",
    deliveryFee: 120,
    featured: true,
    tags: ["Sin TACC", "Seguro", "Variedad"],
    address: "Pocitos, Av. Brasil 2890, Montevideo",
    phone: "+598 2709 8877",
    email: "pedidos@celiacheaven.com.uy"
  },
  {
    id: 11,
    name: "GF Pizza House",
    description: "Las mejores pizzas gluten free de la ciudad. Masa crujiente y deliciosa.",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400",
    category: "gluten-free",
    rating: 4.7,
    deliveryTime: "25-35 min",
    deliveryFee: 0,
    featured: false,
    tags: ["Pizza", "Italiano", "Crujiente"],
    address: "Tres Cruces, Av. 8 de Octubre 3456, Montevideo",
    phone: "+598 2480 5566",
    email: "contacto@gfpizzahouse.com.uy"
  },
  {
    id: 12,
    name: "Pasta Without Limits",
    description: "Pasta fresca sin gluten hecha en casa. Salsas artesanales y recetas italianas.",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400",
    category: "gluten-free",
    rating: 4.6,
    deliveryTime: "40-50 min",
    deliveryFee: 180,
    featured: false,
    tags: ["Pasta", "Artesanal", "Italiano"],
    address: "Carrasco, Av. Arocena 1523, Montevideo",
    phone: "+598 2601 4433",
    email: "reservas@pastawithoutlimits.com.uy"
  },
  {
    id: 29,
    name: "GF Sweet Bakery",
    description: "Pastelería sin gluten artesanal. Brownies, cookies y tortas certificadas sin TACC.",
    image: "https://images.unsplash.com/photo-1587241321921-91a834d82b01?w=400",
    category: "gluten-free",
    rating: 4.9,
    deliveryTime: "25-35 min",
    deliveryFee: 0,
    featured: true,
    tags: ["Pastelería", "Sin TACC", "Dulces"],
    address: "Pocitos, 26 de Marzo 1234, Montevideo",
    phone: "+598 2709 2233",
    email: "info@gfsweetbakery.com.uy"
  },
  {
    id: 30,
    name: "Celiac Friendly Café",
    description: "Café y brunch 100% libre de gluten. Desayunos, sándwiches y smoothies.",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
    category: "gluten-free",
    rating: 4.7,
    deliveryTime: "20-30 min",
    deliveryFee: 100,
    featured: false,
    tags: ["Café", "Brunch", "Desayunos"],
    address: "Malvín, Propios 2890, Montevideo",
    phone: "+598 2618 7766",
    email: "contacto@celiacfriendly.com.uy"
  }
];

module.exports = glutenFreeStores;